### ISSUE TITLE
Publikacja WarsawJS na Medium.com

### ISSUE THREAD

**Issue by mswiecicki** [warsawjs/incubator#2]
# Zarys

Proponuję założenie WarsawJS'owej publikacji na Medium.  
Publikację są czymś w rodzaju wspólnego szyldu pod którym można publikować artykuły. Z takich które pewnie każdy kojarzy mogę podać przykłady _freeCodeCamp_ czy _HackerNoon_.
Meetupy dają Nam wszystkim szansę spróbowania swoich sił jako prelegent, taka publikacja umożliwiła by coś podobnego, ale na polu słowa pisanego.

# Korzyści

- stworzenie przyjaznej przestrzeni dla początkujących, bądź zwyczajnie okazyjnych, bloggerów z naszego community
- prelekcji można zrobić w ciągu roku skończoną ilość - nie ma limitu artykułów, które można by opublikować (chyba)
- pod wspólną egidą można by zapewne liczyć na lepszy zasięg niż publikując coś na medium tak samemu sobie
- duże możliwości crowdsource'owe - ktoś napisze fajny artykuł, ktoś zrobi jakiś proofread, ktoś inny może się zaoferować z tłumaczeniem etc.
- kolejna wspólna przestrzeń / inicjatywa służąca integracji społeczności.

**Comment by piecioshka** [comment]
Dzięki @4rlekin za pomysł! 👍 

Bardzo interesujący pomysł. Fakt tworzenie wspólnego bloga przez społeczność jest kolejną przestrzenią do aktywizacji warszawskich programistów JavaScript - a to jest celem organizacji.

Ze swojej strony proponują, stworzyć subdomenę w stylu https://blog.warsawjs.com/ pod którym mogłyby być osadzone publikacje z Medium.com. Więcej o tym zabiegu dostępne jest tutaj: https://help.medium.com/hc/en-us/articles/115005579728-Get-started-with-custom-domains

Marek, daj znać co myślisz. Obecnie przepisuje Isssue na Ciebie 🙂

**Comment by mswiecicki** [comment]
Myślę że pomysł z subdomeną jest super! Nie miałem pojęcia, że tak się da ;)

Jeden problem jaki w tym widzę wynika z następującego paragrafu:

> Please note that all custom domain owners must pay a one-time charge of $75, which covers setup, an SSL certificate, and ongoing support for domains.

Nie jest to jakaś astronomiczna kwota może, a organizacja ma sponsorów; natomiast zakładam, że albo któryś sponsor musiałby to klepnąć (nie wiem jak wygląda współpraca wprawdzie), albo trzeba by zrobić jakąś zrzutkę.
Tak czy inaczej nie jest to jakaś wielka przeszkoda, ale też trzeba się z tym liczyć.

Niezależnie od powyższego można własną domenę dodać do istniejącej już publikacji.

Skoro issue jest przypisane na mnie, to czy mam rozumieć, że mogę się czuć upoważniony do założenia publikacji na medium ?

**Comment by piecioshka** [comment]
> Jeden problem jaki w tym widzę wynika z następującego paragrafu:
> > Please note that all custom domain owners must pay a one-time charge of $75, which covers setup, an SSL certificate, and ongoing support for domains.

Z takimi kosztami sobie poradzimy dzięki sponsorom. Na ten moment mogę powiedzieć, że nie jest to bloker.

> Skoro issue jest przypisane na mnie, to czy mam rozumieć, że mogę się czuć upoważniony do założenia publikacji na medium ?

Jest przypisane do Ciebie bo czekało na Twoją odpowiedź 😄 

Marek, 
założenie konta to nie jest problem. Oczywiście warto to zrobić (korzystając ze skrzynki `contact [at] warsawjs.com`), jednak - jako opiekun tego tematu - zastanów się proszę nad tym, czy projekt zostanie zaakceptowany przez społeczność?

Samo założenie konta oraz napisanie posta na FB nie załatwi sprawy.
Nie wyobrażam sobie, że nagle społeczność zacznie pisać nie na swoich blogach, tylko pod szyldem WarsawJS.

Nie spiesz się z tym temat. Przemyśl proszę jak chciałbyś taki pomysł "wdrożyć" do społeczności.
Będę czekał na dowolne propozycje.

Jestem wdzięczny za pomoc! 👍

**Comment by rootsher** [comment]
@piecioshka, a czemu mieliby tego nie robić ;). Wydaje mi się, że ważna powinna być "elita" artykułów, że nie każdy może tam wrzucić swój artykuł itd. Istotne będą też wymagania dotyczące artykułu, co musi zawierać, może być przez kogoś redagowany itd., dzięki temu każdy tekst będzie na odpowiednim poziomie, fajnie będzie się go czytało i będzie zawierał wszystkie potrzebne informacje, co nie zawsze można osiągnąć samemu. Jak będzie podany autor wpisu, to why not ;).

PS. Sam bym pisał:p, to zawsze trafia do większego grona odbiorców :), na swoim blogu mogę np. linkować, albo po prostu pisać na inne tematy ;).

PS2. Sory, że się tak wtrącam, po prostu mi wyskoczyło i pomyślałem, że to świetny pomysł !

**Comment by mswiecicki** [comment]
@rootsher Zgodziłbym się że pewien "elitarny" status mógłby dodać postrzeganej wartości i napędzać aspiracje społeczności; uważam natomiast, że tworzenie takowego powinno się odbywać z największą troską o to, aby nie odstraszać i nie traktować nikogo z góry.
Moderacja / redakcja treści na przykład - powinna się odbywać na zasadzie wspierania autora w produkcji najlepszego możliwego contentu, a nie z pozycji: "za słabe, popraw".

Co do pomysłów na wdrożenie to jak do tej pory przyszły mi tylko dwa:

1) Zrobienie jakowejś sondy wśród członków - szczególnie juniorów - naszej społeczności, jakie tematy sprawiają im trudność, jakie mają pytania, wątpliwości czy blockery - i opublikowanie odpowiedzi na takowe long-form właśnie w takiej Mediumowej naszej publikacji. To mogłoby działać w stronę popularyzacji tej inicjatywy wśród społeczności.

2) Mniej lub bardziej oddolne zachęcanie ludzi do rozwoju w ramach pisania artykułu - na zasadzie: chcesz zgłębić ten temat ? może zrób to przy okazji pisania artykułu! Tutaj dodatkowo motywacyjnie można by próbowac jakoś parować ludzi z kimś do pomocy / redakcji / mentorowania.
Ogólnie wydaje mi się, że nawiązywanie do prelekcji może być pewnym wytrychem, bo jak wiemy chętnych na prelekcje jest dużo - a do pisania artykułów jest dużo niższa bariera wejścia.

To chyba najbardziej realne i wykonalne podejścia jakie mi przyszły do głowy. Nie wiem na ile w ogóle możliwe jest aktywne popularyzowanie takiej koncepcji - jak ktoś nie chce pisać to nie będzie i już.

PS. Jakie wtrącam ?? Po to tutaj mamy otwarte issue żeby temat przedyskutować, im więcej osób dorzuci swoje przemyślenia na temat tym lepiej!

**Comment by rkaw92** [comment]
@4rlekin Tak, raczej nikt nie chciałby poczuć się wykluczony. Sądzę, że warto zrobić w ogóle sondę, kto by chciał pisać jakiekolwiek artykuły.
To, z czym wydaje mi się, że będzie duży problem wśród społeczności, to pisanie takich dłuższych treści po angielsku, i tutaj obstawiam, że będzie spędzane 90% czasu "redaktora". Ewentualnie można ustalić, aby pisać na Medium International po polsku.

**Comment by mswiecicki** [comment]
@rkaw92 Szczerze mówiąc od początku wyobrażałem sobie, że treści będą pisane po Polsku - ale tak na dobrą sprawę to już kwestia osobnicza jak komu wygodniej. Można ewentualnie zaznaczyć dla pewności, że dowolny język mile widziany.

Co do sondy to jak najbardziej się zgadzam, tylko gdzie byłoby sensownie taką zrobić ?
Wydaje mi się, że historycznie to te sondy nie cieszą się jakąś powalającą frekwencją - nie jeżeli wziąć pod uwagę ile osób przychodzi na meetup.

Może w ramach ankiety powarsztatowej  jakoś ? Albo na meetupie w jakiś sposób zrobić jakieś głosowanie czy coś...

**Comment by rkaw92** [comment]
@4rlekin Z warsztatami raczej odpada, bo za mało ludzi tam jest. Wskaźnik partycypacji jest co prawda większy, ale nadal większość osób nie dostaje się po prostu na workshopy. Sprytnie byłoby zrobić to na meetupie w stylu podnoszenia rąk na "kto napisał kiedyś techniczny artykuł?" - "a kto by chciał spróbować?".

**Comment by mswiecicki** [comment]
@rkaw92 Coś trzeba by wykombinować, może @piecioshka będzie miał jakieś dobre pomysły, ja nie wiem jak skuteczne są te wszystkie meetup.com'y i facebooki.

Też sobie poniewczasie zdałem sprawę że Piotrek chyba zastanawiał się nad zachęcaniem osób już piszących do publikowania się jako WarsawJS, podczas gdy ja bardziej wyobrażałem sobie aktywację juniorów i osób bardziej doświadczonych, a też niepiszących. To w sumie są dwa różne zagadnienia.

**Comment by piecioshka** [comment]
**Inicjatywa została zaakceptowana** ✅

---

Z dniem 2 lutego 2018 ruszamy!

Zostały wysłane maila do osób chętnych wzięcia udziału w takiej inicjatywie. Oczywiście będziemy zwiększali listę piszących. Na ten moment nie planuję żadnej selekcji osób, więc tak samo jak na meeupie - każdy jest w stanie napisać artykuł.

Więcej szczegółów mailowo lub Slack.

_PS. Na najbliższym meetupie 14 lutego inicjatywa zostanie ogłoszona społeczności._
_Slajdy otwierające spotkanie zostały zaktualizowane: https://github.com/warsawjs/meetup-support-slides/commit/82923c521ce4c1e586813242864ea6a51141ca54_
